// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var ethOracleChainlink = ethers.utils.getAddress("0x0715A7794a1dc8e42615F059dD6e406A6594651A");

var maticOracleChainlink = ethers.utils.getAddress("0xd0D5e3DB44DE05E9F294BB0a3bEEaF030DE24Ada");

var btcOracleChainlink = ethers.utils.getAddress("0x007A22900a3B98143368Bd5906f8E17e9867581b");

var Mumbai = {
  ethOracleChainlink: ethOracleChainlink,
  maticOracleChainlink: maticOracleChainlink,
  btcOracleChainlink: btcOracleChainlink
};

exports.Mumbai = Mumbai;
/* ethOracleChainlink Not a pure module */
