// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var LetOps = require("../test/library/LetOps.js");
var DeployHelpers = require("./DeployHelpers.js");

var avaxOraclePriceFeedAddress = ethers.utils.getAddress("0x0A77230d17318075983913bC2145DB16C7366156");

function launchAvaxMarket(param, deploymentArgs) {
  var treasury = param.treasury;
  var paymentToken = param.paymentToken;
  var longShort = param.longShort;
  var staker = param.staker;
  return LetOps.AwaitThen.let_(Curry._1(deploymentArgs.getNamedAccounts, undefined), (function (namedAccounts) {
                return LetOps.AwaitThen.let_(ethers.getSigners(), (function (loadedAccounts) {
                              var admin = loadedAccounts[1];
                              console.log("deploying markets");
                              return DeployHelpers.deployAvax_Avalanche(longShort, staker, treasury, admin, paymentToken, avaxOraclePriceFeedAddress, deploymentArgs.deployments, namedAccounts);
                            }));
              }));
}

exports.avaxOraclePriceFeedAddress = avaxOraclePriceFeedAddress;
exports.launchAvaxMarket = launchAvaxMarket;
/* avaxOraclePriceFeedAddress Not a pure module */
