// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_exn = require("rescript/lib/js/js_exn.js");
var LetOps = require("../test/library/LetOps.js");
var Globals = require("../test/library/Globals.js");
var CONSTANTS = require("../test/CONSTANTS.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var SyntheticToken = require("../test/library/contracts/SyntheticToken.js");
var YieldManagerMock = require("../test/library/contracts/YieldManagerMock.js");
var OracleManagerMock = require("../test/library/contracts/OracleManagerMock.js");
var OracleManagerChainlink = require("../test/library/contracts/OracleManagerChainlink.js");

var minSenderBalance = Globals.bnFromString("50000000000000000");

var minRecieverBalance = Globals.bnFromString("20000000000000000");

function topupBalanceIfLow(from, to_) {
  return LetOps.AwaitThen.let_(from.getBalance(), (function (senderBalance) {
                if (Globals.bnLt(senderBalance, minSenderBalance)) {
                  Js_exn.raiseError("WARNING - Sender doesn't have enough eth - need at least 0.05 ETH! (top up to over 1 ETH to be safe)");
                }
                return LetOps.Await.let_(to_.getBalance(), (function (recieverBalance) {
                              if (Globals.bnLt(recieverBalance, minRecieverBalance)) {
                                from.sendTransaction({
                                      to_: to_.address,
                                      value: minRecieverBalance
                                    });
                                return ;
                              }
                              
                            }));
              }));
}

function updateSystemState(longShort, admin, marketIndex) {
  return longShort.connect(admin).updateSystemState(marketIndex);
}

function mintAndApprove(paymentToken, amount, user, approvedAddress) {
  return LetOps.AwaitThen.let_(paymentToken.mint(user.address, amount), (function (param) {
                return paymentToken.connect(user).approve(approvedAddress, amount);
              }));
}

function stakeSynthLong(amount, longShort, marketIndex, user) {
  return LetOps.AwaitThen.let_(longShort.syntheticTokens(marketIndex, true), (function (longAddress) {
                return LetOps.AwaitThen.let_(SyntheticToken.at(longAddress), (function (synth) {
                              return LetOps.Await.let_(synth.balanceOf(user.address), (function (usersSyntheticTokenBalance) {
                                            if (Globals.bnGt(usersSyntheticTokenBalance, Globals.bnFromString("0"))) {
                                              synth.connect(user).stake(amount);
                                              return ;
                                            }
                                            
                                          }));
                            }));
              }));
}

function executeOnMarkets(marketIndexes, functionToExecute) {
  return Belt_Array.reduce(marketIndexes, Promise.resolve(undefined), (function (previousPromise, marketIndex) {
                return LetOps.AwaitThen.let_(previousPromise, (function (param) {
                              return Curry._1(functionToExecute, marketIndex);
                            }));
              }));
}

function setOracleManagerPrice(longShort, marketIndex, admin) {
  return LetOps.AwaitThen.let_(longShort.oracleManagers(marketIndex), (function (oracleManagerAddr) {
                return LetOps.AwaitThen.let_(OracleManagerMock.at(oracleManagerAddr), (function (oracleManager) {
                              return LetOps.AwaitThen.let_(oracleManager.getLatestPrice(), (function (currentPrice) {
                                            var nextPrice = Globals.div(Globals.mul(currentPrice, Globals.bnFromInt(101)), Globals.bnFromInt(100));
                                            return oracleManager.connect(admin).setPrice(nextPrice);
                                          }));
                            }));
              }));
}

function redeemShortNextPriceWithSystemUpdate(amount, marketIndex, longShort, user, admin) {
  return LetOps.AwaitThen.let_(longShort.connect(user).redeemShortNextPrice(marketIndex, amount), (function (param) {
                return LetOps.AwaitThen.let_(setOracleManagerPrice(longShort, marketIndex, admin), (function (param) {
                              return updateSystemState(longShort, admin, marketIndex);
                            }));
              }));
}

function redeemNextPrice(amount, marketIndex, longShort, user, isLong) {
  var redeemFunction = isLong ? (function (prim0, prim1, prim2) {
        return prim0.redeemLongNextPrice(prim1, prim2);
      }) : (function (prim0, prim1, prim2) {
        return prim0.redeemShortNextPrice(prim1, prim2);
      });
  return Curry._3(redeemFunction, longShort.connect(user), marketIndex, amount);
}

function shiftFromShortNextPriceWithSystemUpdate(amount, marketIndex, longShort, user, admin) {
  return LetOps.AwaitThen.let_(longShort.connect(user).shiftPositionFromShortNextPrice(marketIndex, amount), (function (param) {
                return LetOps.AwaitThen.let_(setOracleManagerPrice(longShort, marketIndex, admin), (function (param) {
                              return longShort.connect(admin).updateSystemState(marketIndex);
                            }));
              }));
}

function shiftFromLongNextPriceWithSystemUpdate(amount, marketIndex, longShort, user, admin) {
  return LetOps.AwaitThen.let_(longShort.connect(user).shiftPositionFromLongNextPrice(marketIndex, amount), (function (param) {
                return LetOps.AwaitThen.let_(setOracleManagerPrice(longShort, marketIndex, admin), (function (param) {
                              return longShort.updateSystemState(marketIndex);
                            }));
              }));
}

function mintLongNextPriceWithSystemUpdate(amount, marketIndex, paymentToken, longShort, user, admin) {
  return LetOps.AwaitThen.let_(mintAndApprove(paymentToken, amount, user, longShort.address), (function (param) {
                return LetOps.AwaitThen.let_(longShort.connect(user).mintLongNextPrice(marketIndex, amount), (function (param) {
                              return LetOps.AwaitThen.let_(setOracleManagerPrice(longShort, marketIndex, admin), (function (param) {
                                            return updateSystemState(longShort, admin, marketIndex);
                                          }));
                            }));
              }));
}

function mintNextPrice(amount, marketIndex, paymentToken, longShort, user, isLong) {
  return LetOps.AwaitThen.let_(paymentToken.connect(user).approve(longShort.address, amount), (function (param) {
                var mintFunction = isLong ? (function (prim0, prim1, prim2) {
                      return prim0.mintLongNextPrice(prim1, prim2);
                    }) : (function (prim0, prim1, prim2) {
                      return prim0.mintShortNextPrice(prim1, prim2);
                    });
                return Curry._3(mintFunction, longShort.connect(user), marketIndex, amount);
              }));
}

function mintShortNextPriceWithSystemUpdate(amount, marketIndex, paymentToken, longShort, user, admin) {
  return LetOps.AwaitThen.let_(mintAndApprove(paymentToken, amount, user, longShort.address), (function (param) {
                return LetOps.AwaitThen.let_(longShort.connect(user).mintShortNextPrice(marketIndex, amount), (function (param) {
                              return LetOps.AwaitThen.let_(setOracleManagerPrice(longShort, marketIndex, admin), (function (param) {
                                            return updateSystemState(longShort, admin, marketIndex);
                                          }));
                            }));
              }));
}

function deployTestMarket(syntheticName, syntheticSymbol, longShortInstance, treasuryInstance, admin, paymentToken) {
  return LetOps.AwaitThen.let_(OracleManagerMock.make(admin.address), (function (oracleManager) {
                return LetOps.AwaitThen.let_(YieldManagerMock.make(longShortInstance.address, treasuryInstance.address, paymentToken.address), (function (yieldManager) {
                              return LetOps.AwaitThen.let_(paymentToken.MINTER_ROLE(), (function (mintRole) {
                                            return LetOps.AwaitThen.let_(paymentToken.grantRole(mintRole, yieldManager.address), (function (param) {
                                                          return LetOps.AwaitThen.let_(longShortInstance.connect(admin).createNewSyntheticMarket(syntheticName, syntheticSymbol, paymentToken.address, oracleManager.address, yieldManager.address), (function (param) {
                                                                        return LetOps.AwaitThen.let_(longShortInstance.latestMarket(), (function (latestMarket) {
                                                                                      var kInitialMultiplier = Globals.bnFromString("1000000000000000000");
                                                                                      var kPeriod = Globals.bnFromInt(0);
                                                                                      return LetOps.AwaitThen.let_(mintAndApprove(paymentToken, Globals.bnFromString("2000000000000000000"), admin, longShortInstance.address), (function (param) {
                                                                                                    var unstakeFee_e18 = Globals.bnFromString("5000000000000000");
                                                                                                    var initialMarketSeedForEachMarketSide = Globals.bnFromString("1000000000000000000");
                                                                                                    return longShortInstance.connect(admin).initializeMarket(latestMarket, kInitialMultiplier, kPeriod, unstakeFee_e18, initialMarketSeedForEachMarketSide, Globals.bnFromInt(5), Globals.bnFromInt(0), Globals.bnFromInt(1), CONSTANTS.tenToThe18);
                                                                                                  }));
                                                                                    }));
                                                                      }));
                                                        }));
                                          }));
                            }));
              }));
}

function deployMumbaiMarket(syntheticName, syntheticSymbol, longShortInstance, treasuryInstance, admin, paymentToken, oraclePriceFeedAddress) {
  return LetOps.AwaitThen.let_(OracleManagerChainlink.make(admin.address, oraclePriceFeedAddress), (function (oracleManager) {
                return LetOps.AwaitThen.let_(YieldManagerMock.make(longShortInstance.address, treasuryInstance.address, paymentToken.address), (function (yieldManager) {
                              return LetOps.AwaitThen.let_(paymentToken.MINTER_ROLE(), (function (mintRole) {
                                            return LetOps.AwaitThen.let_(paymentToken.grantRole(mintRole, yieldManager.address), (function (param) {
                                                          return LetOps.AwaitThen.let_(longShortInstance.connect(admin).createNewSyntheticMarket(syntheticName, syntheticSymbol, paymentToken.address, oracleManager.address, yieldManager.address), (function (param) {
                                                                        return LetOps.AwaitThen.let_(longShortInstance.latestMarket(), (function (latestMarket) {
                                                                                      var kInitialMultiplier = Globals.bnFromString("5000000000000000000");
                                                                                      var kPeriod = Globals.bnFromInt(864000);
                                                                                      return LetOps.AwaitThen.let_(mintAndApprove(paymentToken, Globals.bnFromString("2000000000000000000"), admin, longShortInstance.address), (function (param) {
                                                                                                    var unstakeFee_e18 = Globals.bnFromString("5000000000000000");
                                                                                                    var initialMarketSeedForEachMarketSide = Globals.bnFromString("1000000000000000000");
                                                                                                    return longShortInstance.connect(admin).initializeMarket(latestMarket, kInitialMultiplier, kPeriod, unstakeFee_e18, initialMarketSeedForEachMarketSide, Globals.bnFromInt(5), Globals.bnFromInt(0), Globals.bnFromInt(1), CONSTANTS.tenToThe18);
                                                                                                  }));
                                                                                    }));
                                                                      }));
                                                        }));
                                          }));
                            }));
              }));
}

function deployMumbaiMarketUpgradeable(syntheticName, syntheticSymbol, longShortInstance, stakerInstance, treasuryInstance, admin, paymentToken, oraclePriceFeedAddress, deployments, namedAccounts) {
  return LetOps.AwaitThen.let_(longShortInstance.latestMarket(), (function (latestMarket) {
                var newMarketIndex = latestMarket + 1 | 0;
                return LetOps.AwaitThen.let_(deployments.deploy("SS" + syntheticSymbol, {
                                contract: "SyntheticTokenUpgradeable",
                                from: namedAccounts.deployer,
                                log: true,
                                proxy: {
                                  proxyContract: "UUPSProxy",
                                  execute: {
                                    methodName: "initialize",
                                    args: [
                                      "Float Short " + syntheticName,
                                      "f\xe2\x86\x97\xef\xb8\x8f" + syntheticSymbol,
                                      longShortInstance.address,
                                      stakerInstance.address,
                                      newMarketIndex,
                                      false
                                    ]
                                  }
                                }
                              }), (function (syntheticTokenShort) {
                              return LetOps.AwaitThen.let_(deployments.deploy("SL" + syntheticSymbol, {
                                              from: namedAccounts.deployer,
                                              log: true,
                                              contract: "SyntheticTokenUpgradeable",
                                              proxy: {
                                                proxyContract: "UUPSProxy",
                                                execute: {
                                                  args: [
                                                    "Float Long " + syntheticName,
                                                    "f\xe2\x86\x98\xef\xb8\x8f" + syntheticSymbol,
                                                    longShortInstance.address,
                                                    stakerInstance.address,
                                                    newMarketIndex,
                                                    true
                                                  ],
                                                  methodName: "initialize"
                                                }
                                              }
                                            }), (function (syntheticTokenLong) {
                                            return LetOps.AwaitThen.let_(deployments.deploy("OracleManager" + syntheticSymbol, {
                                                            from: namedAccounts.deployer,
                                                            log: true,
                                                            contract: "OracleManagerChainlinkTestnet",
                                                            args: [
                                                              admin.address,
                                                              oraclePriceFeedAddress,
                                                              Globals.bnFromInt(27)
                                                            ]
                                                          }), (function (oracleManager) {
                                                          console.log("a.1");
                                                          console.log("a.3");
                                                          return LetOps.AwaitThen.let_(deployments.deploy("YieldManager" + syntheticSymbol, {
                                                                          from: namedAccounts.deployer,
                                                                          contract: "YieldManagerAave",
                                                                          log: true,
                                                                          proxy: {
                                                                            proxyContract: "UUPSProxy",
                                                                            execute: {
                                                                              methodName: "initialize",
                                                                              args: [
                                                                                longShortInstance.address,
                                                                                treasuryInstance.address,
                                                                                paymentToken.address,
                                                                                "0x639cB7b21ee2161DF9c882483C9D55c90c20Ca3e",
                                                                                "0x178113104fEcbcD7fF8669a0150721e231F0FD4B",
                                                                                "0xd41aE58e803Edf4304334acCE4DC4Ec34a63C644",
                                                                                0,
                                                                                admin.address
                                                                              ]
                                                                            }
                                                                          }
                                                                        }), (function (yieldManager) {
                                                                        console.log("a.4");
                                                                        console.log([
                                                                              yieldManager.address,
                                                                              syntheticTokenLong.address,
                                                                              syntheticTokenShort.address
                                                                            ]);
                                                                        return LetOps.AwaitThen.let_(longShortInstance.connect(admin).createNewSyntheticMarketExternalSyntheticTokens(syntheticName, syntheticSymbol, syntheticTokenLong.address, syntheticTokenShort.address, paymentToken.address, oracleManager.address, yieldManager.address), (function (param) {
                                                                                      console.log("a.5");
                                                                                      var kInitialMultiplier = Globals.bnFromString("5000000000000000000");
                                                                                      var kPeriod = Globals.bnFromInt(864000);
                                                                                      console.log("a.6");
                                                                                      var unstakeFee_e18 = Globals.bnFromString("5000000000000000");
                                                                                      var initialMarketSeedForEachMarketSide = Globals.bnFromString("1000000000000000000");
                                                                                      return LetOps.AwaitThen.let_(paymentToken.connect(admin).approve(longShortInstance.address, Globals.mul(initialMarketSeedForEachMarketSide, Globals.bnFromInt(3))), (function (param) {
                                                                                                    console.log("a.7");
                                                                                                    return longShortInstance.connect(admin).initializeMarket(newMarketIndex, kInitialMultiplier, kPeriod, unstakeFee_e18, initialMarketSeedForEachMarketSide, Globals.bnFromInt(5), Globals.bnFromInt(0), Globals.bnFromInt(1), CONSTANTS.tenToThe18);
                                                                                                  }));
                                                                                    }));
                                                                      }));
                                                        }));
                                          }));
                            }));
              }));
}

function deployFlipp3ningPolygon(longShortInstance, stakerInstance, treasuryInstance, admin, paymentToken, ethMarketCapOraclePriceFeedAddress, btcMarketCapOraclePriceFeedAddress, deployments, namedAccounts) {
  var syntheticName = "Flipp3ning";
  var syntheticSymbol = "F3";
  return LetOps.AwaitThen.let_(longShortInstance.latestMarket(), (function (latestMarket) {
                var newMarketIndex = latestMarket + 1 | 0;
                return LetOps.AwaitThen.let_(deployments.deploy("SSF3", {
                                contract: "SyntheticTokenUpgradeable",
                                from: namedAccounts.deployer,
                                log: true,
                                proxy: {
                                  proxyContract: "UUPSProxy",
                                  execute: {
                                    methodName: "initialize",
                                    args: [
                                      "Float Short Flipp3ning",
                                      "fsF3",
                                      longShortInstance.address,
                                      stakerInstance.address,
                                      newMarketIndex,
                                      false
                                    ]
                                  }
                                }
                              }), (function (syntheticTokenShort) {
                              return LetOps.AwaitThen.let_(deployments.deploy("SLF3", {
                                              from: namedAccounts.deployer,
                                              log: true,
                                              contract: "SyntheticTokenUpgradeable",
                                              proxy: {
                                                proxyContract: "UUPSProxy",
                                                execute: {
                                                  args: [
                                                    "Float Long Flipp3ning",
                                                    "flF3",
                                                    longShortInstance.address,
                                                    stakerInstance.address,
                                                    newMarketIndex,
                                                    true
                                                  ],
                                                  methodName: "initialize"
                                                }
                                              }
                                            }), (function (syntheticTokenLong) {
                                            return LetOps.AwaitThen.let_(deployments.deploy("OracleManagerF3", {
                                                            from: namedAccounts.deployer,
                                                            log: true,
                                                            contract: "OracleManagerFlipp3ning",
                                                            args: [
                                                              ethMarketCapOraclePriceFeedAddress,
                                                              btcMarketCapOraclePriceFeedAddress
                                                            ]
                                                          }), (function (oracleManager) {
                                                          console.log("a.1");
                                                          console.log("a.3");
                                                          return LetOps.AwaitThen.let_(deployments.deploy("YieldManagerF3", {
                                                                          from: namedAccounts.deployer,
                                                                          contract: "YieldManagerAave",
                                                                          log: true,
                                                                          proxy: {
                                                                            proxyContract: "UUPSProxy",
                                                                            execute: {
                                                                              methodName: "initialize",
                                                                              args: [
                                                                                longShortInstance.address,
                                                                                treasuryInstance.address,
                                                                                paymentToken.address,
                                                                                "0x27F8D03b3a2196956ED754baDc28D73be8830A6e",
                                                                                "0xd05e3E715d945B59290df0ae8eF85c1BdB684744",
                                                                                "0x357D51124f59836DeD84c8a1730D72B749d8BC23",
                                                                                0,
                                                                                admin.address
                                                                              ]
                                                                            }
                                                                          }
                                                                        }), (function (yieldManager) {
                                                                        console.log("a.4");
                                                                        console.log([
                                                                              yieldManager.address,
                                                                              syntheticTokenLong.address,
                                                                              syntheticTokenShort.address
                                                                            ]);
                                                                        return LetOps.AwaitThen.let_(longShortInstance.connect(admin).createNewSyntheticMarketExternalSyntheticTokens(syntheticName, syntheticSymbol, syntheticTokenLong.address, syntheticTokenShort.address, paymentToken.address, oracleManager.address, yieldManager.address), (function (param) {
                                                                                      console.log("a.5");
                                                                                      var kInitialMultiplier = Globals.bnFromString("2000000000000000000");
                                                                                      var kPeriod = Globals.bnFromInt(5184000);
                                                                                      console.log("a.6");
                                                                                      var unstakeFee_e18 = Globals.bnFromString("5000000000000000");
                                                                                      var initialMarketSeedForEachMarketSide = Globals.bnFromString("1000000000000000000");
                                                                                      return LetOps.AwaitThen.let_(paymentToken.connect(admin).approve(longShortInstance.address, Globals.mul(initialMarketSeedForEachMarketSide, Globals.bnFromInt(3))), (function (param) {
                                                                                                    console.log("a.7");
                                                                                                    return longShortInstance.connect(admin).initializeMarket(newMarketIndex, kInitialMultiplier, kPeriod, unstakeFee_e18, initialMarketSeedForEachMarketSide, Globals.bnFromInt(5), Globals.bnFromInt(0), Globals.bnFromInt(1), Globals.mul(Globals.bnFromInt(3), CONSTANTS.tenToThe18));
                                                                                                  }));
                                                                                    }));
                                                                      }));
                                                        }));
                                          }));
                            }));
              }));
}

exports.minSenderBalance = minSenderBalance;
exports.minRecieverBalance = minRecieverBalance;
exports.topupBalanceIfLow = topupBalanceIfLow;
exports.updateSystemState = updateSystemState;
exports.mintAndApprove = mintAndApprove;
exports.stakeSynthLong = stakeSynthLong;
exports.executeOnMarkets = executeOnMarkets;
exports.setOracleManagerPrice = setOracleManagerPrice;
exports.redeemShortNextPriceWithSystemUpdate = redeemShortNextPriceWithSystemUpdate;
exports.redeemNextPrice = redeemNextPrice;
exports.shiftFromShortNextPriceWithSystemUpdate = shiftFromShortNextPriceWithSystemUpdate;
exports.shiftFromLongNextPriceWithSystemUpdate = shiftFromLongNextPriceWithSystemUpdate;
exports.mintLongNextPriceWithSystemUpdate = mintLongNextPriceWithSystemUpdate;
exports.mintNextPrice = mintNextPrice;
exports.mintShortNextPriceWithSystemUpdate = mintShortNextPriceWithSystemUpdate;
exports.deployTestMarket = deployTestMarket;
exports.deployMumbaiMarket = deployMumbaiMarket;
exports.deployMumbaiMarketUpgradeable = deployMumbaiMarketUpgradeable;
exports.deployFlipp3ningPolygon = deployFlipp3ningPolygon;
/* minSenderBalance Not a pure module */
